name: CI Pipeline - Sistema de Medidas

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Criar artefato de deploy
        run: zip -r sistema-medidas.zip frontend/build
      - uses: actions/upload-artifact@v3
        with:
          name: sistema-medidas
          path: sistema-medidas.zip
